### ISSUE TITLE
A way to use alias on 2 fields with same key but different input fields

### ISSUE THREAD

**Issue by petar-bursic-sprawsm** [cfpinto/graphql#12]
Hi,

I tried building a query with aliases used for 2 fields with same name but different input attributes:

```php
$collection = new Query('collection', ['id' => 'gid://shopify/Collection/'.$collectionID]);
$productsAttributes = ['first' => 40];
$query = $collection->use('id')
    ->products($productsAttributes)->edges->use('cursor')
    ->node->use('id','title')
    ->variants(['first' => 6])
    ->edges->node->use('id','title')
    ->metafield(['namespace' => 'my_namespace', 'key' => 'active'])->alias('active')->use('id','value')
    ->prev()->metafield(['namespace' => 'my_namespace', 'key' => 'components'])->alias('config')->use('id','value')
    ->root()->query();
```

But this will ignore the first "metafield" and buld the alias only for the second one:

```GraphQL
{
    collection(id: "gid:\/\/shopify\/Collection\/261375557685") {
        id
        products(first: 40) {
            edges {
                cursor
                node {
                    id
                    title
                    variants(first: 6) {
                        edges {
                            node {
                                id
                                title
                                config: metafield(namespace: "my_namespace" key: "components") {
                                    id
                                    value
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

Is there a way to have 2 'metafield' attributes with different aliases?
The goal is to have this:

```GraphQL
variants(first:6){
  edges {
    node {
      id
      title
      active: metafield(namespace: "my_namespace", key: "active") {
        id
        value
      }
      config: metafield(namespace: "my_namespace", key: "components") {
        id
        value
      }
    }
  }
}
```

**Comment by cfpinto** [comment]
Hi. I will look into this over the weekend. Just to confirm are you using the latest version?

**Comment by petar-bursic-sprawsm** [comment]
Hi.

Sorry, I didn't catch this on Friday.
Yes, I'm using:
`"name": "cfpinto/graphql",
"version": "1.0.0",`

My current solution is a bit of a workaround where I have to remove couple of curly braces and I would like to have a way not to do that:

` $collection = new Query('collection', ['id' => 'gid://shopify/Collection/'.$collectionID]);
$active = new Node('metafield',['namespace' => 'my_namespace', 'key' => 'active']);
        $active->use('id','value')->alias('active');
        $query = $collection->use('id')
            ->products($productsAttributes)->edges->use('cursor')
            ->node->use('id','title')
            ->variants(['first' => 6])
                ->edges->node->use('id','title')
                    ->$active
                    ->prev()->metafield(['namespace' => 'my_namespace', 'key' => 'components'])->alias('config')->use('id','value')
            ->prev()->prev()->prev()->prev()->prev()->prev()->pageInfo->use('hasNextPage')
            ->root()->query();
        $query = preg_replace ("/\{\n\s*\}/","",$query);//TODO - find a better way to use 2 aliases on the same field (metafield)
`

This way I get the correct query:

`{
    collection(id: "gid:\/\/shopify\/Collection\/261375557685") {
        id
        products(first: 40) {
            edges {
                cursor
                node {
                    id
                    title
                    variants(first: 6) {
                        edges {
                            node {
                                id
                                title
                                active: metafield(namespace: "my_namespace" key: "active") {
                                    id
                                    value
                                }
                                
                                config: metafield(namespace: "my_namespace" key: "components") {
                                    id
                                    value
                                }
                            }
                        }
                    }
                }
            }
            pageInfo {
                hasNextPage
            }
        }
    }
}`

Without the "preg_replace" part, I would get this:

`...
edges {
    node {
        id
        title
        active: metafield(namespace: "delta_bundles" key: "active") {
            id
            value
        }
        {
        }
        config: metafield(namespace: "delta_bundles" key: "components") {
            id
            value
        }
    }
}
...`

**Comment by cfpinto** [comment]
hey. I found a way how you can do what you want and will push it out soon. However I would stick with the native GraphQL way https://graphql.org/learn/queries/#meta-fields for future proofing your implementation. metafields is the way to go intead of duplicating the node via alias

**Comment by petar-bursic-sprawsm** [comment]
Thanks a lot!
