### ISSUE TITLE
[BUG]: Mutation with multiple variables

### ISSUE THREAD

**Issue by wajdijurry** [cfpinto/graphql#7]
I am trying to create a mutation query:
```
$mutation = new Mutation('create', ['var1' => new Variable('var1', 'Uuid!', '']);
```

This throws an exception: `Call to member 'addVariable' on null`, Node.php:311
```
    protected function buildArgs($arguments)
    {
        $builder = new Arguments($arguments);
        
        $query = $builder->convert();

        foreach ($builder->getVariables() as $variable) {
            $this->getRootNode()->addVariable($variable);
        }

        return $query;
    }
```

I am wondered why this happen? Is there a solution or am I doing something wrong ?

**Update**
The mutation query is not created in proper way, I'll show an example:
This query generated by this library:
```
mutation {
  create(category: "Create!", storeId: "Uuid!", userId: "Uuid!") {
    id
    name
    url
    order
    attributes {
      id
      key
      name
      values
    }
    children {
      id
      name
    }
  }
}
```

While it should look like this one (I wrote it manually):
```
mutation Mutate($category: Create!, $storeId: Uuid!, $userId: Uuid!) {
    create(category: $category, storeId: $storeId, userId: $userId) {
        id
        name
        parent {
            id
            name
        }
        attributes {
            id
            name
            values
        }
    }
}
```

**Comment by cfpinto** [comment]
hey. thanks for your feedback.

Couple os questions:

1. what is the return type of `$this->getRootNode()`?
2. What is the code used to generate the invalid mutation?

I need to be able to replicate in order to fix or suggest implementation
